name: powersync

services:
  # MongoDB Service used internally
  mongo:
    container_name: mongo
    image: mongo:7.0
    command: --replSet rs0 --bind_ip_all --quiet
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db

  # Initializes the MongoDB replica set. This service will not usually be actively running
  mongo-rs-init:
    container_name: mongo-rs-init
    image: mongo:7.0
    depends_on:
      - mongo
    restart: on-failure
    entrypoint:
      - bash
      - -c
      - 'mongosh --host mongo:27017 --eval ''try{rs.status().ok && quit(0)} catch {} rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host : "mongo:27017" }]})'''

  # Start PowerSync with Mongo healthchecks
  powersync:
    container_name: powersync-service
    restart: unless-stopped
    image: journeyapps/powersync-service:latest
    depends_on:
      mongo-rs-init:
        condition: service_completed_successfully
    command: ["start", "-r", "unified"]
    volumes:
      - ../powersync:/powersync
    environment:
      POWERSYNC_CONFIG_PATH: /powersync/config.yaml
      PS_PG_URI: postgres://${PG_DATABASE_USER}:${PG_DATABASE_PASSWORD}@${PG_DATABASE_HOSTNAME}:${PG_DATABASE_PORT}/${PG_DATABASE_NAME}
      PS_MONGO_URI: mongodb://mongo:27017/powersync
      PS_PORT: ${PS_PORT}
    ports:
      - ${PS_PORT}:${PS_PORT}

volumes:
  mongo_storage:
